const loginHostResponse = {
	accessToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjA5bWVyZGFuMTBAZ21haWwuY29tIiwiaWQiOjIsInJvbGVzIjpbInVzZXIiXSwiaWF0IjoxNjUxNDI0MDgyLCJleHAiOjE2NTE1MTA0ODJ9.tWJeZrPsm0V4_2ia680jVvQTZVpPYPRZVlVq6_O-MAY",
	refreshToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjA5bWVyZGFuMTBAZ21haWwuY29tIiwiaWQiOjIsInJvbGVzIjpbInVzZXIiXSwiaWF0IjoxNjUxNDI0MDgyLCJleHAiOjE2NTQwMTYwODJ9.Dc4SYTvjtf29XZP5pBKkDHRM3jtkzjUie7Pcw1LyMmI"
}

export default loginHostResponse